# .github/workflows/lint.yml
name: Lint & Format Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install ruff (linter)
        run: pip install ruff

      - name: Run linter
        run: ruff check src/ tests/ examples/
